// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Author
    public class Author
    {
        public long AuthorId { get; set; } // AuthorId (Primary key)
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Books where [Book].[AuthorId] point to this entity (FK_Book_Author)
        /// </summary>
        public virtual ICollection<Book> Books { get; set; } // Book.FK_Book_Author

        public Author()
        {
            Books = new List<Book>();
        }
    }

}
// </auto-generated>
