// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // BookView
    public class BookView
    {
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public long BookId { get; set; } // BookId
        public string Title { get; set; } // Title (length: 250)
        public string Description { get; set; } // Description (length: 500)
        public byte[] Cover { get; set; } // Cover
        public string BarCode { get; set; } // BarCode (length: 250)
        public bool IsAvailable { get; set; } // IsAvailable
        public bool IsReserved { get; set; } // IsReserved
    }

}
// </auto-generated>
