// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // Book
    public class Book
    {
        public long BookId { get; set; } // BookId (Primary key)
        public string Title { get; set; } // Title (length: 250)
        public long AuthorId { get; set; } // AuthorId
        public string Description { get; set; } // Description (length: 500)
        public string Cover { get; set; } // Cover (length: 500)
        public string BarCode { get; set; } // BarCode (length: 250)
        public int IsAvailable { get; set; } // IsAvailable

        // Reverse navigation

        /// <summary>
        /// Child Borrows where [Borrows].[UserId] point to this entity (FK_Borrows_Book)
        /// </summary>
        public virtual ICollection<Borrow> Borrows { get; set; } // Borrows.FK_Borrows_Book

        /// <summary>
        /// Child CommentsBooks where [CommentsBook].[BookId] point to this entity (FK_CommentsBook_Book)
        /// </summary>
        public virtual ICollection<CommentsBook> CommentsBooks { get; set; } // CommentsBook.FK_CommentsBook_Book

        // Foreign keys

        /// <summary>
        /// Parent Author pointed by [Book].([AuthorId]) (FK_Book_Author)
        /// </summary>
        public virtual Author Author { get; set; } // FK_Book_Author

        public Book()
        {
            Borrows = new List<Borrow>();
            CommentsBooks = new List<CommentsBook>();
        }
    }

}
// </auto-generated>
