// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Lib.Shared.Data.Entities
{
    // BookView
    public class BookViewConfiguration : IEntityTypeConfiguration<BookView>
    {
        public void Configure(EntityTypeBuilder<BookView> builder)
        {
            builder.ToView("BookView", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.BookId).HasColumnName(@"BookId").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("varchar(250)").IsRequired().IsUnicode(false).HasMaxLength(250);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar(500)").IsRequired().IsUnicode(false).HasMaxLength(500);
            builder.Property(x => x.Cover).HasColumnName(@"Cover").HasColumnType("varbinary(max)").IsRequired(false);
            builder.Property(x => x.BarCode).HasColumnName(@"BarCode").HasColumnType("varchar(250)").IsRequired().IsUnicode(false).HasMaxLength(250);
            builder.Property(x => x.IsAvailable).HasColumnName(@"IsAvailable").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsReserved).HasColumnName(@"IsReserved").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
