// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // Borrows
    public class Borrow
    {
        public long BookId { get; set; } // BookId (Primary key)
        public long UserId { get; set; } // UserId (Primary key)
        public DateTime LoanDate { get; set; } // LoanDate (Primary key)
        public long ReturnDate { get; set; } // ReturnDate (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Book pointed by [Borrows].([UserId]) (FK_Borrows_Book)
        /// </summary>
        public virtual Book Book { get; set; } // FK_Borrows_Book

        /// <summary>
        /// Parent User pointed by [Borrows].([UserId]) (FK_Borrows_User)
        /// </summary>
        public virtual User User { get; set; } // FK_Borrows_User
    }

}
// </auto-generated>
