// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Lib.Shared.Data.Entities
{
    // BorrowView
    public class BorrowViewConfiguration : IEntityTypeConfiguration<BorrowView>
    {
        public void Configure(EntityTypeBuilder<BorrowView> builder)
        {
            builder.ToView("BorrowView", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.BookId).HasColumnName(@"BookId").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.LoanDate).HasColumnName(@"LoanDate").HasColumnType("date").IsRequired();
            builder.Property(x => x.ReturnDate).HasColumnName(@"ReturnDate").HasColumnType("date").IsRequired();
            builder.Property(x => x.RentalPeriod).HasColumnName(@"RentalPeriod").HasColumnType("int").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("varchar(250)").IsRequired().IsUnicode(false).HasMaxLength(250);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar(500)").IsRequired().IsUnicode(false).HasMaxLength(500);
            builder.Property(x => x.Cover).HasColumnName(@"Cover").HasColumnType("varbinary(max)").IsRequired(false);
            builder.Property(x => x.BarCode).HasColumnName(@"BarCode").HasColumnType("varchar(250)").IsRequired().IsUnicode(false).HasMaxLength(250);
            builder.Property(x => x.IsAvailable).HasColumnName(@"IsAvailable").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsReserved).HasColumnName(@"IsReserved").HasColumnType("bit").IsRequired();
            builder.Property(x => x.AuthorId).HasColumnName(@"AuthorId").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.Email).HasColumnName(@"Email").HasColumnType("varchar(100)").IsRequired().IsUnicode(false).HasMaxLength(100);
        }
    }

}
// </auto-generated>
