// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // CommentsBook
    public class CommentsBook
    {
        public long BookId { get; set; } // BookId (Primary key)
        public long CommentId { get; set; } // CommentId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Book pointed by [CommentsBook].([BookId]) (FK_CommentsBook_Book)
        /// </summary>
        public virtual Book Book { get; set; } // FK_CommentsBook_Book

        /// <summary>
        /// Parent Comment pointed by [CommentsBook].([CommentId]) (FK_CommentsBook_Comment)
        /// </summary>
        public virtual Comment Comment { get; set; } // FK_CommentsBook_Comment
    }

}
// </auto-generated>
