// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // Comment
    public class Comment
    {
        public long CommentId { get; set; } // CommentId (Primary key)
        public long UserId { get; set; } // UserId
        public string Description { get; set; } // Description (length: 250)
        public DateTime AddingDate { get; set; } // AddingDate
        public int Mark { get; set; } // Mark

        // Reverse navigation

        /// <summary>
        /// Child CommentsBooks where [CommentsBook].[CommentId] point to this entity (FK_CommentsBook_Comment)
        /// </summary>
        public virtual ICollection<CommentsBook> CommentsBooks { get; set; } // CommentsBook.FK_CommentsBook_Comment

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Comment].([UserId]) (FK_Comment_User)
        /// </summary>
        public virtual User User { get; set; } // FK_Comment_User

        public Comment()
        {
            CommentsBooks = new List<CommentsBook>();
        }
    }

}
// </auto-generated>
