// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Lib.Shared.Data.Entities
{
    // CommentsBook
    public class CommentsBookConfiguration : IEntityTypeConfiguration<CommentsBook>
    {
        public void Configure(EntityTypeBuilder<CommentsBook> builder)
        {
            builder.ToTable("CommentsBook", "dbo");
            builder.HasKey(x => new { x.BookId, x.CommentId });

            builder.Property(x => x.BookId).HasColumnName(@"BookId").HasColumnType("bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CommentId).HasColumnName(@"CommentId").HasColumnType("bigint").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.Book).WithMany(b => b.CommentsBooks).HasForeignKey(c => c.BookId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_CommentsBook_Book");
            builder.HasOne(a => a.Comment).WithMany(b => b.CommentsBooks).HasForeignKey(c => c.CommentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_CommentsBook_Comment");
        }
    }

}
// </auto-generated>
