// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace Lib.Shared.Data.Entities
{
    public class DatabaseContextFactory : IDesignTimeDbContextFactory<DatabaseContext>
    {
        public DatabaseContext CreateDbContext(string[] args)
        {
            return new DatabaseContext();
        }
    }
}
// </auto-generated>
