// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // User
    public class User
    {
        public long UserId { get; set; } // UserId (Primary key)
        public long RoleId { get; set; } // RoleId
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string PasswordHash { get; set; } // PasswordHash (length: 250)
        public string Class { get; set; } // Class (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] UserImg { get; set; } // UserImg

        // Reverse navigation

        /// <summary>
        /// Child Borrows where [Borrows].[UserId] point to this entity (FK_Borrows_User)
        /// </summary>
        public virtual ICollection<Borrow> Borrows { get; set; } // Borrows.FK_Borrows_User

        /// <summary>
        /// Child Comments where [Comment].[UserId] point to this entity (FK_Comment_User)
        /// </summary>
        public virtual ICollection<Comment> Comments { get; set; } // Comment.FK_Comment_User

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [User].([RoleId]) (FK_User_Role)
        /// </summary>
        public virtual Role Role { get; set; } // FK_User_Role

        public User()
        {
            Borrows = new List<Borrow>();
            Comments = new List<Comment>();
        }
    }

}
// </auto-generated>
