// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lib.Shared.Data.Entities
{
    // UserView
    public class UserView
    {
        public string RoleName { get; set; } // RoleName (length: 50)
        public long UserId { get; set; } // UserId
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string PasswordHash { get; set; } // PasswordHash (length: 250)
        public string Class { get; set; } // Class (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] UserImg { get; set; } // UserImg
        public long RoleId { get; set; } // RoleId
    }

}
// </auto-generated>
